### ISSUE TITLE
why-curry 一文中echo_param例子不当

### ISSUE THREAD

**Issue by c19** [luochen1990/luochen1990.github.io#1]
Python中应这样实现：

``` Python
def echo_params(func):
    def wrap(*arg, **kwarg):
        print(arg, kwarg)
        return func(*arg, **kwarg)
    return wrap
```

这样使用

``` Python
echo_func = echo_params(origin_func)
```

或者作为decorator

``` Python
@echo_params
def origin_func(...):
```

**Comment by luochen1990** [comment]
除了你把变量名字换了，我没有看出哪里有区别啊？

**Comment by c19** [comment]
喔，看漏了。
"你都得考虑你的 参数函数f 在面临各种传参方式的情况下要怎么处理"
这句话什么意思。echo_params不是不管什么参数都输出吗。根本不用管参数有多少。是什么。

**Comment by luochen1990** [comment]
你没有看到另一种可能，另一种可能是，如果参数是个结构化的参数，整个函数是单参函数的话，其实不需要写成 `f(*a, **d)` 这样，直接 `f(x)` 就可以了。 我说的就是，这里要麻烦一些，而且很多时候很容易忘记。 再比如你定义一个恒等函数叫 `identity`， `identity = lambda x: x` 这是最直接的想法是吧，你原本期望这个函数对参数什么都不做，然而有些时候却发现，它把参数变少了。

**Comment by luochen1990** [comment]
你没有看到另一种可能，另一种可能是，如果参数是个结构化的参数，整个函数是单参函数的话，其实不需要写成 f(_a, *_d) 这样，直接 f(x) 就可以了。 我说的就是，这里要麻烦一些，而且很多时候很容易忘记。 再比如你定义一个恒等函数叫 identity， identity = lambda x: x 这是最直接的想法是吧，你原本期望这个函数对参数什么都不做，然而有些时候却发现，它把参数变少了。
