### ISSUE TITLE
回答你在知乎上的一个提问

### ISSUE THREAD

**Issue by dou4cc** [luochen1990/luochen1990.github.io#2]
传送门：https://www.zhihu.com/question/38130483

不在知乎上直接回答你是因为我不想实名，不实名什么都做不了。

-----------------

有一个很dirty hack的方法可以做到，所有现代浏览器都支持。因为依赖的是一个底层的设计上的侧信道，在以后的很多日子里不会被干掉。

你看indexedDB文档的话就会发现里面有很多全局锁，很多锁的释放非常激进，和GC挂钩。比如IDBOpenDBRequest，即使你不close，GC也会帮你close。而IDBOpenDBRequest会阻塞indexedDB.deleteDatabase。代码我不想写了，太dirty。聪明的你要是写出来了通知我一下。

**Comment by luochen1990** [comment]
好吧, 谢谢你.
我两年前问这个问题是因为更早之前我想实现一个自己的FRP库, 然后苦于事件监听器的注销问题, 不注销的话会有严重的GC问题, 所以才纠结于寻找在JS中定义析构函数的办法.

现在感觉在JS这种语言里做点有趣的事情太难了, 最近已经转而折腾Idris了, 所以也就不纠结这些trick的问题了.

**Comment by dou4cc** [comment]
我刚刚顺着自己的思路实现出来了：https://github.com/dou4cc/code/blob/master/ondestruct.js

却发现已经不凑效了~
